#!/bin/bash
#
# From https://github.com/Smarker/jupyter-githook-sample/blob/master/.githooks/pre-commit
#

set -euo pipefail

IPYNB_FILE_PATHS=`git diff --staged --name-only | awk "/.\.ipynb/"`
PROJECT_ROOT_PATH=`git rev-parse --show-toplevel`

function get_script_extension() {
    file_path=$1
    echo $(cat $file_path | jq -r '.metadata.file_extension')
}

if [[ -n "$IPYNB_FILE_PATHS" ]]; then
    echo "Saving changes to these notebooks: $IPYNB_FILE_PATHS"
    for ipynb_file_path in $IPYNB_FILE_PATHS
    do
        file_no_extension="${ipynb_file_path%.*}"

        # if file exists and is not a checkpoint file
        if [[ -f "$ipynb_file_path" ]] && [[ "$ipynb_file_path" != *"checkpoint"* ]]; then
              echo "Creating html from notebook..."
            jupyter nbconvert --to html "$ipynb_file_path"
        fi
    done
fi

# add the newly created files to the current commit
git add -A
